# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    hob.token.privatekey: ~
    hob.token.publickey: ~
    hob.token.passphrase: ~
    hob.token.header.authorization.prefix: 'Bearer'
    hob.token.header.authorization.name: 'Authorization'

services:

#### SERVICES #####
    hob.token.encoder:
        class: HOB\TokenBundle\Encoder\JWTEncoder
        arguments: ['%hob.token.privatekey%','%hob.token.publickey%','%hob.token.passphrase%']

    hob.token.extractor.authorization:
        class: HOB\TokenBundle\TokenExtractor\AuthorizationHeaderTokenExtractor
        arguments: ['%hob.token.header.authorization.prefix%','%hob.token.header.authorization.name%']

    hob.token.builder:
        class: HOB\TokenBundle\Builder\TokenBuilder
        arguments: ['@hob.token.encoder']

    hob.token.storage:
        class: HOB\TokenBundle\Storage\TokenStorage
        arguments: ['@hob.token.encoder']

#### LISTENERS ####
    hob.token.listener.store_token:
        class: HOB\TokenBundle\Listener\StoreTokenListener
        arguments: [ '%hob_token.config.required%', '@hob.token.storage', '@hob.token.extractor.authorization', '@hob.token.builder']
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 0 }
